import { RentalProduct, RentalBooking, AppNotification, DamageDispute } from './types';

export const EGYPT_GOVERNORATES = [
  { en: 'Ismailia', ar: 'الإسماعيلية' },
  { en: 'Cairo', ar: 'القاهرة' },
  { en: 'Giza', ar: 'الجيزة' },
  { en: 'Alexandria', ar: 'الإسكندرية' },
  { en: 'Port Said', ar: 'بورسعيد' },
  { en: 'Suez', ar: 'السويس' },
  { en: 'Dakahlia', ar: 'الدقهلية' },
  { en: 'Sharqia', ar: 'الشرقية' },
];

export const CATEGORIES_LIST = [
  {
    id: 'Fashion & Clothing',
    nameEn: 'Fashion & Clothing',
    nameAr: 'الأزياء والملابس',
    icon: 'Shirt',
    image: 'https://images.unsplash.com/photo-1594938298603-c8148c4dae35?auto=format&fit=crop&w=600&q=80',
    count: 24,
  },
  {
    id: 'Furniture',
    nameEn: 'Furniture',
    nameAr: 'الأثاث',
    icon: 'Armchair',
    image: 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=600&q=80',
    count: 18,
  },
  {
    id: 'Home Appliances',
    nameEn: 'Home Appliances',
    nameAr: 'الأجهزة المنزلية',
    icon: 'Refrigerator',
    image: 'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
    count: 35,
  },
  {
    id: 'Furnishings',
    nameEn: 'Furnishings',
    nameAr: 'المفروشات والديكور',
    icon: 'Sparkles',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=600&q=80',
    count: 15,
  },
  {
    id: 'Electronics',
    nameEn: 'Electronics',
    nameAr: 'الإلكترونيات',
    icon: 'Tv',
    image: 'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=600&q=80',
    count: 42,
  },
  {
    id: 'Cameras & Photography',
    nameEn: 'Cameras & Photography',
    nameAr: 'الكاميرات والتصوير',
    icon: 'Camera',
    image: 'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=600&q=80',
    count: 29,
  },
  {
    id: 'Tools & Equipment',
    nameEn: 'Tools & Equipment',
    nameAr: 'العدد والمعدات',
    icon: 'Wrench',
    image: 'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80',
    count: 31,
  },
  {
    id: 'Events & Party Equipment',
    nameEn: 'Events & Party Equipment',
    nameAr: 'مستلزمات الحفلات والمناسبات',
    icon: 'PartyPopper',
    image: 'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=600&q=80',
    count: 22,
  },
  {
    id: 'Sports & Outdoor',
    nameEn: 'Sports & Outdoor',
    nameAr: 'الرياضة والتخييم',
    icon: 'Compass',
    image: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=600&q=80',
    count: 19,
  },
  {
    id: 'Other',
    nameEn: 'Other',
    nameAr: 'أخرى ومتنوعات',
    icon: 'Package',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=600&q=80',
    count: 12,
  },
];

export const INITIAL_PRODUCTS: RentalProduct[] = [
  {
    id: 'rh-prod-01',
    name: 'Philips Azur Steam Iron Pro',
    nameAr: 'مكواة بخار فيليبس آزور برو 3000 واط',
    category: 'Home Appliances',
    categoryAr: 'الأجهزة المنزلية',
    brand: 'Philips',
    model: 'GC4909/60 Azur',
    purchaseYear: 2023,
    usageDuration: '8 months',
    usageDurationAr: '8 أشهر',
    condition: 'Like New',
    conditionAr: 'بحالة ممتازة كالجديد',
    originalPrice: 4200,
    dailyPrice: 50,
    weeklyPrice: 280,
    securityDeposit: 500,
    isAvailable: true,
    governorate: 'Ismailia',
    governorateAr: 'الإسماعيلية',
    area: 'Al Sheikh Zayed',
    areaAr: 'الشيخ زايد',
    images: [
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewsCount: 38,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-01',
    ownerName: 'Tarek Mansour',
    ownerNameAr: 'طارق منصور',
    ownerRating: 4.95,
    ownerCompletedRentals: 47,
    specifications: {
      'Power': '3000 Watts',
      'Steam Boost': '250g/min continuous',
      'Soleplate': 'SteamGlide Elite scratch-resistant',
      'Cord Length': '2.5 meters swivel',
      'Auto-Off': 'Safety automatic shutdown',
    },
    specificationsAr: {
      'القدرة الكهربائية': '3000 واط',
      'دفع البخار': '250 جم/دقيقة مستمر',
      'قاعدة المكواة': 'ستيم جلايد إليت مقاومة للخدش',
      'طول السلك': '2.5 متر مع دوران حر',
      'إيقاف تلقائي': 'نظام أمان إيقاف ذاتي',
    },
    includedAccessories: [
      'Original filling cup / كوب الملء الأصلي',
      'Heat-resistant protective storage sleeve / حقيبة حرارية للحفظ',
    ],
    knownDefects: 'No defects, microscopic hairline cosmetic sign on handle',
    previousRepairs: 'None, fully factory sealed',
    warranty: 'Under official manufacturer warranty until Dec 2026',
    serialNumber: 'PH-AZ-99214-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 94,
      visibleDamage: 'Zero structural flaws; minor cosmetic sheen on cord',
      visibleDamageAr: 'خالية من العيوب الهيكلية، علامات طفيفة على السلك الخارجي',
      completeness: 'Complete with original cup',
      completenessAr: 'مكتملة الملحقات مع الكوب الأصلي',
      imageQuality: 'High Definition multi-angle',
      imageQualityAr: 'عالية الدقة من عدة زوايا موثقة',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for premium catalog',
      recommendationAr: 'جاهزة للنشر في القائمة الموثوقة',
      analyzedAt: '2026-03-01',
    },
  },
  {
    id: 'rh-prod-02',
    name: 'Sony Alpha A7 IV Full-Frame Camera Kit',
    nameAr: 'كاميرا سوني A7 IV فل فريم مع عدسة 24-70mm GM',
    category: 'Cameras & Photography',
    categoryAr: 'الكاميرات والتصوير',
    brand: 'Sony',
    model: 'ILCE-7M4 + FE 24-70mm f/2.8 GM',
    purchaseYear: 2024,
    usageDuration: '4 months',
    usageDurationAr: '4 أشهر',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً',
    originalPrice: 125000,
    dailyPrice: 750,
    weeklyPrice: 4200,
    securityDeposit: 3000,
    isAvailable: true,
    governorate: 'Cairo',
    governorateAr: 'القاهرة',
    area: 'New Cairo (Tagamoa)',
    areaAr: 'التجمع الخامس',
    images: [
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1502982720700-bfff97f2ecac?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1512790182412-b19e6d62bc39?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 5.0,
    reviewsCount: 52,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-02',
    ownerName: 'Ahmed El-Sayed (Director of Photography)',
    ownerNameAr: 'أحمد السيد (مدير تصوير)',
    ownerRating: 4.98,
    ownerCompletedRentals: 84,
    specifications: {
      'Sensor': '33MP Full-Frame Exmor R CMOS',
      'Video': '4K 60p 10-bit 4:2:2 All-Intra',
      'Autofocus': 'Real-time Eye AF (Human, Animal, Bird)',
      'Memory': 'Dual Slot CFexpress Type A / SD UHS-II',
    },
    specificationsAr: {
      'المستشعر': '33 ميجابكسل فل فريم إكسمور R',
      'الفيديو': '4K بسرعة 60 إطار في الثانية 10-بت',
      'التركيز التلقائي': 'تتبع فوري للعين بالذكاء الاصطناعي',
      'الذاكرة': 'منفذان لبطاقات SD و CFexpress',
    },
    includedAccessories: [
      '3x Sony NP-FZ100 batteries',
      'Dual rapid charger',
      'Peak Design camera strap',
      '128GB Pro V90 SD Card',
      'Pelican waterproof protective hardcase',
    ],
    warranty: 'Sony Egypt official warranty until 2027',
    serialNumber: 'SN-SNY-884910-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 98,
      visibleDamage: 'Clean sensor, pristine glass optics, zero scratches',
      visibleDamageAr: 'مستشعر نظيف جداً، عدسات سليمة دون أدنى خدش',
      completeness: 'Complete package with 3 batteries and hardcase',
      completenessAr: 'باقة كاملة مع 3 بطاريات وحقيبة مقاومة للصدمات',
      imageQuality: 'Verified 4K optical scan',
      imageQualityAr: 'فحص رقمي دقيق عالي الوضوح',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Verified Pro Tier listing',
      recommendationAr: 'تم التوثيق ضمن الفئة الاحترافية العليا',
      analyzedAt: '2026-02-15',
    },
  },
  {
    id: 'rh-prod-03',
    name: 'Sony PlayStation 5 Console + 2 DualSense Controllers',
    nameAr: 'بلايستيشن 5 مع ذراعين تحكم و 4 ألعاب حديثة',
    category: 'Electronics',
    categoryAr: 'الإلكترونيات',
    brand: 'Sony PlayStation',
    model: 'PS5 Slim Disc Edition 1TB',
    purchaseYear: 2024,
    usageDuration: '6 months',
    usageDurationAr: '6 أشهر',
    condition: 'Like New',
    conditionAr: 'بحالة ممتازة كالجديد',
    originalPrice: 38000,
    dailyPrice: 200,
    weeklyPrice: 1100,
    securityDeposit: 1500,
    isAvailable: true,
    governorate: 'Giza',
    governorateAr: 'الجيزة',
    area: 'Dokki',
    areaAr: 'الدقي',
    images: [
      'https://images.unsplash.com/photo-1606813907291-d86efa9b94db?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    reviewsCount: 64,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-03',
    ownerName: 'Omar Farouk',
    ownerNameAr: 'عمر فاروق',
    ownerRating: 4.89,
    ownerCompletedRentals: 31,
    specifications: {
      'Storage': '1TB Ultra-High Speed NVMe SSD',
      'Output': '4K 120Hz HDR HDMI 2.1',
      'Audio': 'Tempest 3D AudioTech',
      'Controllers': '2x DualSense with Haptic Feedback',
    },
    specificationsAr: {
      'سعة التخزين': '1 تيرابايت فائق السرعة SSD',
      'دقة العرض': '4K بسرعة 120 إطار مع تقنية HDR',
      'الصوت': 'صوت ثلاثي الأبعاد Tempest 3D',
      'وحدات التحكم': 'ذراعان DualSense مع ردود فعل لمسية',
    },
    includedAccessories: [
      '2x DualSense Wireless Controllers',
      'Ultra High Speed HDMI cable',
      'Dual controller charging dock',
      'Installed: EA FC 25, Spider-Man 2, Gran Turismo 7',
    ],
    serialNumber: 'PS5-SL-901248-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 92,
      visibleDamage: 'Zero scratches on faceplates; controller analog sticks firm',
      visibleDamageAr: 'خالية من الخدوش، عصا التحكم في حالة ممتازة ومشدودة',
      completeness: 'Complete with cables and games',
      completenessAr: 'مكتملة بجميع الوصلات والشاحن والألعاب',
      imageQuality: 'Clear serial & port verification',
      imageQualityAr: 'توثيق واضح للرقم التسلسلي والمنافذ',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for instant rental',
      recommendationAr: 'تم الاعتماد للتأجير الفوري',
      analyzedAt: '2026-02-28',
    },
  },
  {
    id: 'rh-prod-04',
    name: 'DeWalt 20V MAX Cordless Hammer Drill & Impact Driver Combo',
    nameAr: 'طقم شنيور وهيلتي ديوالت 20 فولت بطاريتين مع شنطة عِدد',
    category: 'Tools & Equipment',
    categoryAr: 'العدد والمعدات',
    brand: 'DeWalt',
    model: 'DCK280C2 20V Max Lithium Drill/Driver',
    purchaseYear: 2023,
    usageDuration: '1 year',
    usageDurationAr: 'سنة واحدة',
    condition: 'Very Good',
    conditionAr: 'جيد جداً وقوي',
    originalPrice: 16500,
    dailyPrice: 120,
    weeklyPrice: 650,
    securityDeposit: 800,
    isAvailable: true,
    governorate: 'Alexandria',
    governorateAr: 'الإسكندرية',
    area: 'Smouha',
    areaAr: 'سموحة',
    images: [
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1572981779307-38b8cabb2407?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewsCount: 29,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-04',
    ownerName: 'Hesham Nour',
    ownerNameAr: 'هشام نور',
    ownerRating: 4.92,
    ownerCompletedRentals: 62,
    specifications: {
      'Voltage': '20V MAX',
      'Motor': 'High performance brushless motor',
      'Torque': '300 Unit Watts Out (UWO)',
      'Chuck Size': '1/2 inch ratcheting single sleeve',
    },
    specificationsAr: {
      'الجهد': '20 فولت ماكس',
      'المحرك': 'محرك براشلس عالي الكفاءة',
      'العزم': '300 واط مخرجات عزم قوية',
      'ظرف الشنيور': 'نصف بوصة معدني سريع التغيير',
    },
    includedAccessories: [
      '2x 20V 2.0Ah XR Batteries',
      'Rapid charger',
      '30-piece masonry & steel drill bit set',
      'Heavy-duty tool bag',
    ],
    serialNumber: 'DW-20V-771239-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 89,
      visibleDamage: 'Normal light jobsite scuffs on outer rubber bumpers',
      visibleDamageAr: 'آثار استخدام طبيعية خفيفة على الإطار المطاطي الخارجي',
      completeness: 'All 30 drill bits and 2 batteries included',
      completenessAr: 'جميع البنط الـ 30 والبطاريتين متوفرة وتم فحصها',
      imageQuality: 'Good multi-face inspection',
      imageQualityAr: 'صور واضحة للمحرك والبطاريات',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved with condition documented',
      recommendationAr: 'تمت الموافقة مع تسجيل الملاحظات الطفيفة',
      analyzedAt: '2026-01-20',
    },
  },
  {
    id: 'rh-prod-05',
    name: 'Luxury Royal Wedding Gown / Dress with Veil',
    nameAr: 'فستان زفاف ملكي فاخر مع طرحة مطرزة بالكامل',
    category: 'Fashion & Clothing',
    categoryAr: 'الأزياء والملابس',
    brand: 'La Mariée Haute Couture',
    model: 'Royal Pearl Embellished A-Line',
    purchaseYear: 2024,
    usageDuration: 'Worn 1 time',
    usageDurationAr: 'ارتداء ليلة واحدة فقط',
    condition: 'Like New',
    conditionAr: 'كالجديد بعد تنظيف جاف معقم',
    originalPrice: 45000,
    dailyPrice: 900,
    weeklyPrice: 3800,
    securityDeposit: 2000,
    isAvailable: true,
    governorate: 'Cairo',
    governorateAr: 'القاهرة',
    area: 'Heliopolis (Misr El-Gedida)',
    areaAr: 'مصر الجديدة',
    images: [
      'https://images.unsplash.com/photo-1594552072238-b8a33785b261?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1546804784-896d0dca3805?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 5.0,
    reviewsCount: 19,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-05',
    ownerName: 'Nouran Mostafa',
    ownerNameAr: 'نوران مصطفى',
    ownerRating: 5.0,
    ownerCompletedRentals: 21,
    specifications: {
      'Size': 'Medium (Adjustable corset 38-42)',
      'Fabric': 'French Lace, Silk Tulle & Hand-stitched Swarovski Pearls',
      'Veil': '3-meter cathedral length embroidered veil',
      'Sanitization': 'Professional eco-friendly dry-cleaned and sealed',
    },
    specificationsAr: {
      'المقاس': 'وسط (كورسيه قابل للتعديل مقاس 38 - 42)',
      'الخامة': 'دانتيل فرنسي وتول حريري مطرز بلؤلؤ سواروفسكي',
      'الطرحة': 'طرحة كاتدرائية طول 3 أمتار بتطريز متناسق',
      'التعقيم': 'تنظيف جاف احترافي ومعقم في غلاف حفظ محكم',
    },
    includedAccessories: [
      '3-meter pearl veil',
      'Custom petticoat (جمالون منفوش)',
      'Protective moisture-proof garment bag',
    ],
    serialNumber: 'LM-WED-55410-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 99,
      visibleDamage: 'Flawless fabric, no snags, pristine white tone',
      visibleDamageAr: 'قماش سليم 100%، خالي من أي شد أو بقع، تطريز محكم',
      completeness: 'Complete with matching veil & petticoat',
      completenessAr: 'مكتمل بالطرحة والجمالون وحقيبة الحفظ',
      imageQuality: 'HD macro textile inspection',
      imageQualityAr: 'فحص مجهري دقيق لنسيج الدانتيل',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for VIP bridal rentals',
      recommendationAr: 'معتمد للإيجار الفاخر للمناسبات',
      analyzedAt: '2026-02-10',
    },
  },
  {
    id: 'rh-prod-06',
    name: 'DJ & Event Sound System: 2x JBL EON 15" Powered Speakers + Mixer',
    nameAr: 'ساوند سيستم حفلات متكامل: سماعتين JBL 15 بوصة مع مكسر ومايكين',
    category: 'Events & Party Equipment',
    categoryAr: 'مستلزمات الحفلات والمناسبات',
    brand: 'JBL Professional',
    model: 'EON715 1300W + Behringer 1204USB Mixer',
    purchaseYear: 2023,
    usageDuration: '1 year',
    usageDurationAr: 'سنة واحدة',
    condition: 'Very Good',
    conditionAr: 'جيد جداً مع حقائب حماية',
    originalPrice: 58000,
    dailyPrice: 650,
    weeklyPrice: 3200,
    securityDeposit: 2500,
    isAvailable: true,
    governorate: 'Port Said',
    governorateAr: 'بورسعيد',
    area: 'Al Sharq',
    areaAr: 'حي الشرق',
    images: [
      'https://images.unsplash.com/photo-1464366400600-7168b8af9bc3?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewsCount: 41,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-06',
    ownerName: 'Kareem Shaker',
    ownerNameAr: 'كريم شاكر',
    ownerRating: 4.94,
    ownerCompletedRentals: 58,
    specifications: {
      'Peak Power': '2x 1300 Watts peak class-D',
      'Bluetooth': 'Bluetooth 5.0 streaming & DSP control',
      'Mixer': '12-input analog mixer with built-in effects & USB interface',
      'Microphones': '2x UHF Wireless Shure-compatible handheld mics',
    },
    specificationsAr: {
      'القدرة': '2x 1300 واط صوت نقي ومحيطي',
      'البلوتوث': 'بلوتوث 5.0 للتشغيل والتحكم الرقمي',
      'المكسر': 'مكسر 12 قناة مع مؤثرات صوتية وUSB',
      'الميكروفونات': '2 مايك لاسلكي UHF عالي الحساسية',
    },
    includedAccessories: [
      '2x heavy-duty steel tripod speaker stands',
      '2x wireless mics + batteries',
      'All balanced XLR and power extension cables',
      'Padded travel cases',
    ],
    serialNumber: 'JBL-EON-44192-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 91,
      visibleDamage: 'Minor wear on stand feet; drivers & cones 100% intact',
      visibleDamageAr: 'استخدام طبيعي على حوامل السماعات، المكبرات سليمة تماماً',
      completeness: 'Complete bundle verified with all audio cables',
      completenessAr: 'حزمة متكاملة تم فحص جميع الكابلات والمايكات',
      imageQuality: 'High fidelity audio diagnostic audio clip attached',
      imageQualityAr: 'مرفق فحص نبرة الصوت والموجات الصوتية',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for events and venues',
      recommendationAr: 'معتمد لحفلات الزفاف والمؤتمرات',
      analyzedAt: '2026-02-18',
    },
  },
  {
    id: 'rh-prod-07',
    name: 'Kärcher K5 Premium Pressure Washer 145 Bar',
    nameAr: 'ماكينة غسيل بالضغط العالي كارشر K5 ألماني 145 بار',
    category: 'Home Appliances',
    categoryAr: 'الأجهزة المنزلية',
    brand: 'Kärcher',
    model: 'K5 Premium Smart Control',
    purchaseYear: 2024,
    usageDuration: '5 months',
    usageDurationAr: '5 أشهر',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً',
    originalPrice: 22000,
    dailyPrice: 160,
    weeklyPrice: 850,
    securityDeposit: 900,
    isAvailable: true,
    governorate: 'Ismailia',
    governorateAr: 'الإسماعيلية',
    area: 'Ferdan Road',
    areaAr: 'طريق الفردان',
    images: [
      'https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.85,
    reviewsCount: 24,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-01',
    ownerName: 'Tarek Mansour',
    ownerNameAr: 'طارق منصور',
    ownerRating: 4.95,
    ownerCompletedRentals: 47,
    specifications: {
      'Pressure': '145 Bar max water pressure',
      'Water Flow': '500 Liters / hour',
      'Hose Length': '10 meters high-pressure reinforced hose',
      'Lance': '3-in-1 Multi Jet nozzle with soap dispenser',
    },
    specificationsAr: {
      'ضغط المياه': '145 بار ضغط مياه مركز',
      'معدل التدفق': '500 لتر في الساعة',
      'طول الخرطوم': '10 أمتار مع بكرة لف مدمجة',
      'فوهة الرش': 'مسدس 3 في 1 متعدد الأوضاع مع موزع الصابون',
    },
    includedAccessories: [
      'Dirt blaster nozzle',
      'Foam cannon attachment',
      'Water filter attachment',
      '10m high-pressure reel',
    ],
    serialNumber: 'KRC-K5-10294-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 93,
      visibleDamage: 'Zero leaks, motor pressure seal verified',
      visibleDamageAr: 'لا توجد أي تسريبات، فحص سلامة ضغط المحرك ممتاز',
      completeness: 'All 3 nozzles present',
      completenessAr: 'جميع الرؤوس وفلتر المياه الأصلي موجود',
      imageQuality: 'HD pressure gauge video verified',
      imageQualityAr: 'فيديو تشغيلي للضغط موثق بنجاح',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for rent',
      recommendationAr: 'معتمد وجاهز للتأجير الفوري',
      analyzedAt: '2026-02-25',
    },
  },
  {
    id: 'rh-prod-08',
    name: 'DJI Mini 4 Pro Drone Fly More Combo with RC 2 Screen',
    nameAr: 'طائرة تصوير درون DJI ميني 4 برو مع ريموت بشاشة وبطاريات إضافية',
    category: 'Cameras & Photography',
    categoryAr: 'الكاميرات والتصوير',
    brand: 'DJI',
    model: 'Mini 4 Pro Fly More Combo',
    purchaseYear: 2024,
    usageDuration: '3 months',
    usageDurationAr: '3 أشهر',
    condition: 'Like New',
    conditionAr: 'كالجديد دون أي هبوط خشن',
    originalPrice: 62000,
    dailyPrice: 550,
    weeklyPrice: 2900,
    securityDeposit: 2500,
    isAvailable: true,
    governorate: 'Suez',
    governorateAr: 'السويس',
    area: 'Port Tawfiq',
    areaAr: 'بور توفيق',
    images: [
      'https://images.unsplash.com/photo-1527977966376-1c8408f9f108?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1473968512647-3e447244af8f?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 5.0,
    reviewsCount: 33,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-07',
    ownerName: 'Mahmoud Barakat',
    ownerNameAr: 'محمود بركات',
    ownerRating: 5.0,
    ownerCompletedRentals: 39,
    specifications: {
      'Weight': 'Under 249g ultra-light',
      'Camera': '4K/60fps HDR True Vertical Shooting',
      'Obstacle Sensing': 'Omnidirectional obstacle avoidance',
      'Transmission': 'DJI O4 up to 20km FHD transmission',
    },
    specificationsAr: {
      'الوزن': 'أقل من 249 جرام سهل الحمل',
      'الكاميرا': 'تصوير 4K/60fps عمودي وأفقي حقيقي',
      'حساسات العوائق': 'تجنب الاصطدام من جميع الاتجاهات 360',
      'مدى البث': 'نظام O4 حتى 20 كم بث مباشر FHD',
    },
    includedAccessories: [
      'DJI RC 2 Remote Controller with 5.5" FHD Screen',
      '3x Intelligent Flight Batteries',
      'Two-Way Charging Hub',
      'Shoulder bag & extra propellers',
      'ND Filter Set (ND16/64/256)',
    ],
    serialNumber: 'DJI-M4P-881903-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 97,
      visibleDamage: 'Propellers pristine, gimbal optical motor balanced',
      visibleDamageAr: 'المراوح بحالة الوكالة، محرك الجيمبال متزن وبصريات نقية',
      completeness: 'Fly More package 100% complete with ND filters',
      completenessAr: 'باقة فلاي مور كاملة مع فلاتر ND والحقيبة',
      imageQuality: 'Telemetry logs verified',
      imageQualityAr: 'سجل الطيران وبيانات البطاريات مفحوصة',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for licensed operators',
      recommendationAr: 'معتمد للمصورين المحترفين',
      analyzedAt: '2026-02-27',
    },
  },
  {
    id: 'rh-prod-09',
    name: 'Coleman 6-Person Weatherproof Camping Tent & Outdoor Gear',
    nameAr: 'خيمة تخييم كولمان 6 أفراد مقاومة للمطر والرياح مع مستلزماتها',
    category: 'Sports & Outdoor',
    categoryAr: 'الرياضة والتخييم',
    brand: 'Coleman',
    model: 'Sundome 6-Person WeatherTec',
    purchaseYear: 2023,
    usageDuration: 'Used on 4 trips',
    usageDurationAr: 'استخدمت في 4 رحلات فقط',
    condition: 'Very Good',
    conditionAr: 'جيد جداً ومعقمة',
    originalPrice: 14000,
    dailyPrice: 130,
    weeklyPrice: 650,
    securityDeposit: 600,
    isAvailable: true,
    governorate: 'Dakahlia',
    governorateAr: 'الدقهلية',
    area: 'Mansoura (Geish St)',
    areaAr: 'المنصورة (شارع الجيش)',
    images: [
      'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1510312305653-8ed496efae75?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.8,
    reviewsCount: 16,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-08',
    ownerName: 'Mostafa Kamel',
    ownerNameAr: 'مصطفى كامل',
    ownerRating: 4.88,
    ownerCompletedRentals: 26,
    specifications: {
      'Capacity': '6 Persons comfortably',
      'Setup Time': 'Easy 10-minute setup with snag-free continuous pole sleeves',
      'Weather Protection': 'WeatherTec system with inverted seams & welded floors',
      'Ventilation': 'Ground vent and large mesh windows for airflow',
    },
    specificationsAr: {
      'السعة': 'تسع 6 أشخاص براحة تامة',
      'وقت التركيب': '10 دقائق تركيب سهل مع أعمدة فيبر مرنة',
      'مقاومة الطقس': 'نظام WeatherTec ضد الأمطار والرياح',
      'التهوية': 'نوافذ شبكية كبيرة تمنع الحشرات وتسمح بالتهوية',
    },
    includedAccessories: [
      'Heavy-duty ground tarp / مشمع أرضي عازل للرطوبة',
      '2x Camping LED lanterns / فانوسان إضاءة ليد للشحن',
      'Steel ground pegs & hammer / أوتاد تثبيت فولاذية ومطرقة',
      'Durable carry bag with zipper',
    ],
    serialNumber: 'CLM-SD6-99231-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 90,
      visibleDamage: 'Zero tears, zippers slide smoothly, seam seals intact',
      visibleDamageAr: 'لا توجد أي تمزقات، السوست تعمل بسلاسة، عزل الخياطة سليم',
      completeness: 'Complete with poles, stakes, and lanterns',
      completenessAr: 'مكتملة بجميع الأوتاد والأعمدة والفوانيس',
      imageQuality: 'Tension and fabric integrity verified',
      imageQualityAr: 'تم التحقق من تماسك القماش ومرونة الأعمدة',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for outdoor adventurers',
      recommendationAr: 'معتمد لرحلات التخييم والسفاري',
      analyzedAt: '2026-01-30',
    },
  },
  {
    id: 'rh-prod-10',
    name: 'Modern Ergonomic Office Chair Herman Miller Style',
    nameAr: 'كرسي مكتب طبي مريح متعدد التعديلات لدعم الظهر والرقبة',
    category: 'Furniture',
    categoryAr: 'الأثاث',
    brand: 'ErgoComfort Pro',
    model: 'MasterMesh High-Back',
    purchaseYear: 2024,
    usageDuration: '6 months',
    usageDurationAr: '6 أشهر',
    condition: 'Like New',
    conditionAr: 'كالجديد بدون خدوش',
    originalPrice: 19500,
    dailyPrice: 95,
    weeklyPrice: 480,
    securityDeposit: 600,
    isAvailable: true,
    governorate: 'Cairo',
    governorateAr: 'القاهرة',
    area: 'Maadi',
    areaAr: 'المعادي',
    images: [
      'https://images.unsplash.com/photo-1580481077195-c3a821a58875?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.75,
    reviewsCount: 18,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-02',
    ownerName: 'Ahmed El-Sayed',
    ownerNameAr: 'أحمد السيد',
    ownerRating: 4.98,
    ownerCompletedRentals: 84,
    specifications: {
      'Lumbar Support': 'Dynamic 3D adaptive lumbar',
      'Armrests': '4D adjustable (height, angle, depth, width)',
      'Recline': 'Synchronized recline up to 135 degrees with lock',
      'Base': 'Heavy-duty polished aluminum 5-star base',
    },
    specificationsAr: {
      'دعم الفقرات': 'دعم قطني متكيف ثلاثي الأبعاد أسفل الظهر',
      'مساند اليد': 'رباعية الأبعاد قابلة للتعديل بجميع الاتجاهات',
      'الإمالة': 'إمالة هيدروليكية حتى 135 درجة مع قفل أمان',
      'القاعدة': 'ألومنيوم مقوى خماسي الأرجل مع عجلات صامتة',
    },
    includedAccessories: [
      'Magnetic adjustable headrest',
      'Hardwood floor silent roller wheels',
    ],
    serialNumber: 'ERGO-CHR-30129-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 95,
      visibleDamage: 'Mesh tight and spotless; hydraulic lift verified',
      visibleDamageAr: 'الشبك الطبي مشدود ونظيف تماماً، المساعد الهيدروليكي ممتاز',
      completeness: 'Complete with headrest and roller castors',
      completenessAr: 'مكتمل بمسند الرأس والعجلات الأصلية',
      imageQuality: '360 degree mechanism scan',
      imageQualityAr: 'فحص ميكانيكي شامل لوظائف الحركة',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for home and office rentals',
      recommendationAr: 'معتمد للمكاتب والعمل عن بُعد',
      analyzedAt: '2026-02-14',
    },
  },
  {
    id: 'rh-prod-11',
    name: 'BenQ 4K HDR Home Cinema Projector 3000 ANSI Lumens',
    nameAr: 'بروجكتور سينما منزلي بينكيو 4K عالي السطوع 3000 لومن',
    category: 'Electronics',
    categoryAr: 'الإلكترونيات',
    brand: 'BenQ',
    model: 'TK850i True 4K HDR with Android TV',
    purchaseYear: 2024,
    usageDuration: '4 months',
    usageDurationAr: '4 أشهر (120 ساعة تشغيل فقط)',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً مع الشاشة المتنقلة',
    originalPrice: 72000,
    dailyPrice: 420,
    weeklyPrice: 2200,
    securityDeposit: 2000,
    isAvailable: true,
    governorate: 'Sharqia',
    governorateAr: 'الشرقية',
    area: 'Zagazig (Al Qawmiya)',
    areaAr: 'الزقازيق (القومية)',
    images: [
      'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1595769816263-9b910be24d5f?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.95,
    reviewsCount: 27,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-03',
    ownerName: 'Omar Farouk',
    ownerNameAr: 'عمر فاروق',
    ownerRating: 4.89,
    ownerCompletedRentals: 31,
    specifications: {
      'Resolution': 'True 4K UHD 3840 x 2160',
      'Brightness': '3000 ANSI Lumens for ambient light viewing',
      'Color Space': '98% Rec.709 with HDR-PRO technology',
      'Smart System': 'Built-in Google certified Android TV',
    },
    specificationsAr: {
      'دقة العرض': '4K حقيقي 3840 في 2160 بكسل',
      'السطوع': '3000 لومن وضوح سينمائي حتى مع إضاءة الغرفة',
      'الألوان': 'تقنية HDR-PRO وتغطية 98% لألوان السينما',
      'النظام الذكي': 'أندرويد تي في مدمج وريموت صوتي ذكي',
    },
    includedAccessories: [
      '100-inch portable tripod projection screen / شاشة عرض 100 بوصة مع حامل',
      'Remote control with backlight',
      'High-speed 5m HDMI 2.1 braided cable',
      'Padded shockproof carrying case',
    ],
    serialNumber: 'BNQ-4K-77182-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 96,
      visibleDamage: 'Optical glass clear, zero dust specks in lens array',
      visibleDamageAr: 'العدسة البصرية نقية وخالية من الأتربة أو الخدوش',
      completeness: 'Complete with Android dongle and 100" screen',
      completenessAr: 'مكتمل بالشاشة 100 بوصة والريموت وحقيبة الصدمات',
      imageQuality: 'Sharp optical projection pattern test passed',
      imageQualityAr: 'اجتاز اختبار الحدة وتوزيع الإضاءة البصري',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for movie nights and matches',
      recommendationAr: 'معتمد للسينما المنزلية ومباريات الكرة',
      analyzedAt: '2026-02-22',
    },
  },
  {
    id: 'rh-prod-12',
    name: 'Bose S1 Pro+ Wireless Portable PA Speaker System',
    nameAr: 'مكبر صوت متنقل احترافي بوز S1 برو بلس مع بطارية 11 ساعة',
    category: 'Electronics',
    categoryAr: 'الإلكترونيات',
    brand: 'Bose',
    model: 'S1 Pro+ Wireless All-in-One',
    purchaseYear: 2024,
    usageDuration: '5 months',
    usageDurationAr: '5 أشهر',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً',
    originalPrice: 39000,
    dailyPrice: 280,
    weeklyPrice: 1450,
    securityDeposit: 1200,
    isAvailable: true,
    governorate: 'Ismailia',
    governorateAr: 'الإسماعيلية',
    area: 'Al Montazah',
    areaAr: 'حي المنتزه',
    images: [
      'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewsCount: 22,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-01',
    ownerName: 'Tarek Mansour',
    ownerNameAr: 'طارق منصور',
    ownerRating: 4.95,
    ownerCompletedRentals: 47,
    specifications: {
      'Battery': 'Rechargeable lithium-ion up to 11 hours playtime',
      'Mixer': 'Built-in 3-channel mixer with OLED displays',
      'Wireless': 'Integrated wireless transmitters for mic and guitar',
      'Weight': 'Only 6.5 kg with comfortable ergonomic handle',
    },
    specificationsAr: {
      'البطارية': 'بطارية ليثيوم تدوم حتى 11 ساعة تشغيل متواصل',
      'المكسر': 'مكسر مدمج 3 قنوات مع شاشات OLED رقمية',
      'لاسلكي': 'دعم الإرسال اللاسلكي للمايك والآلات الموسيقية',
      'الوزن': 'وزن خفيف 6.5 كجم مع مقبض حمل مريح',
    },
    includedAccessories: [
      'Bose Wireless Mic Transmitter',
      'Power charging cable',
      'Heavy-duty slip cover',
    ],
    serialNumber: 'BSE-S1P-66129-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 95,
      visibleDamage: 'Pristine metal grille, zero dents',
      visibleDamageAr: 'الشبكة المعدنية سليمة تماماً وبدون أي صدمات',
      completeness: 'Complete with wireless transmitter',
      completenessAr: 'مكتمل بالمرسل اللاسلكي وغطاء الحماية الأصلي',
      imageQuality: 'Acoustic sweep frequency verified',
      imageQualityAr: 'فحص الترددات الصوتية والبطارية بنجاح',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for live acoustic & conferences',
      recommendationAr: 'معتمد للمناسبات والاجتماعات والعروض',
      analyzedAt: '2026-02-12',
    },
  },
  {
    id: 'rh-prod-13',
    name: 'Zhiyun Crane 3S Heavy-Duty Camera Gimbal Stabilizer',
    nameAr: 'مانع اهتزاز احترافي للسينما زيون كرين 3S يتحمل حتى 6.5 كجم',
    category: 'Cameras & Photography',
    categoryAr: 'الكاميرات والتصوير',
    brand: 'Zhiyun-Tech',
    model: 'Crane 3S Pro Cinema Stabilizer',
    purchaseYear: 2023,
    usageDuration: '1 year',
    usageDurationAr: 'سنة واحدة',
    condition: 'Very Good',
    conditionAr: 'جيد جداً وبحالة ممتازة',
    originalPrice: 36000,
    dailyPrice: 290,
    weeklyPrice: 1500,
    securityDeposit: 1400,
    isAvailable: true,
    governorate: 'Cairo',
    governorateAr: 'القاهرة',
    area: 'Nasr City',
    areaAr: 'مدينة نصر',
    images: [
      'https://images.unsplash.com/photo-1589872782433-4f9116e0388a?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.88,
    reviewsCount: 31,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-02',
    ownerName: 'Ahmed El-Sayed',
    ownerNameAr: 'أحمد السيد',
    ownerRating: 4.98,
    ownerCompletedRentals: 84,
    specifications: {
      'Payload': 'Up to 6.5 kg cinema payload capacity',
      'Motors': 'Redesigned high-torque brushless motors',
      'Handle': 'SmartSling handle with control buttons',
      'Locking': 'Zero-shake axis lock system for safe transport',
    },
    specificationsAr: {
      'سعة الحمولة': 'يتحمل حتى 6.5 كجم لكاميرات السينما والعدسات الثقيلة',
      'المحركات': 'محركات عزم خارقة بزاوية دوران مائلة 55 درجة',
      'المقبض': 'مقبض SmartSling ذكي مع شاشة تحكم وإعدادات سريعة',
      'نظام القفل': 'أقفال محكمة لكل محور لمنع الاهتزاز أثناء النقل',
    },
    includedAccessories: [
      'TransMount Image Transmission Transmitter',
      'Focus & Zoom servo motors',
      '3x 18650 high-drain batteries & charger',
      'Heavy-duty foam carry case',
    ],
    serialNumber: 'ZHN-CR3S-99120-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 92,
      visibleDamage: 'Normal clamp contact marks; motor calibration 100%',
      visibleDamageAr: 'علامات طفيفة عند مشبك الكاميرا، معايرة المحاور ممتازة',
      completeness: 'Complete with focus motors and transmission module',
      completenessAr: 'مكتمل بموتور الفوكس وجهاز البث اللاسلكي',
      imageQuality: 'Mechanical torque balance test passed',
      imageQualityAr: 'اجتاز اختبار عزم الدوران والتوازن الميكانيكي',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for commercial film shoots',
      recommendationAr: 'معتمد لتصوير الإعلانات والأفلام',
      analyzedAt: '2026-01-28',
    },
  },
  {
    id: 'rh-prod-14',
    name: 'Portable Gasoline Inverter Generator 2200W Silent Honda',
    nameAr: 'مولد كهرباء بنزين صامت متنقل هوندا 2200 واط إنفرتر للأجهزة الحساسة',
    category: 'Tools & Equipment',
    categoryAr: 'العدد والمعدات',
    brand: 'Honda',
    model: 'EU22i Super Quiet Inverter',
    purchaseYear: 2024,
    usageDuration: '3 months (35 hours)',
    usageDurationAr: '3 أشهر (35 ساعة تشغيل)',
    condition: 'Like New',
    conditionAr: 'كالجديد وصوته هادئ جداً',
    originalPrice: 48000,
    dailyPrice: 320,
    weeklyPrice: 1700,
    securityDeposit: 1800,
    isAvailable: true,
    governorate: 'Giza',
    governorateAr: 'الجيزة',
    area: 'Sheikh Zayed City',
    areaAr: 'مدينة الشيخ زايد',
    images: [
      'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.95,
    reviewsCount: 14,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-04',
    ownerName: 'Hesham Nour',
    ownerNameAr: 'هشام نور',
    ownerRating: 4.92,
    ownerCompletedRentals: 62,
    specifications: {
      'Max Output': '2200 Watts pure sine wave inverter power',
      'Noise Level': 'Super quiet 48-57 dBA (quieter than conversation)',
      'Run Time': 'Up to 8.1 hours on single 3.6L tank (Eco-Throttle)',
      'Weight': 'Lightweight 21.1 kg with easy-carry handle',
    },
    specificationsAr: {
      'القدرة القصوى': '2200 واط موجة جيبية نقية آمنة للابتوب والكاميرات',
      'مستوى الضجيج': 'فائق الهدوء 48 إلى 57 ديسيبل لا يسبب إزعاج',
      'مدة التشغيل': 'حتى 8.1 ساعة بتنك وقود 3.6 لتر بنظام توفير البنزين',
      'الوزن': 'وزن خفيف 21.1 كجم يسهل حمله وتخزينه في السيارة',
    },
    includedAccessories: [
      '12V DC battery charging cable',
      'Oil funnel and spark plug wrench',
      'Full protective weather cover',
    ],
    serialNumber: 'HND-EU22-54019-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 94,
      visibleDamage: 'Clean fuel lines, zero oil leaks, fresh oil change',
      visibleDamageAr: 'خراطيم وقود نظيفة وخالية من أي تسريب، زيت جديد',
      completeness: 'Complete with accessories and tool kit',
      completenessAr: 'مكتمل بأسلاك الشحن ومفتاح الصيانة والغطاء',
      imageQuality: 'Voltage stability digital log verified',
      imageQualityAr: 'تم التحقق من استقرار الجهد الكهربائي 220V',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for outdoor camps & shoots',
      recommendationAr: 'معتمد للمخيمات والتصوير الخارجي والطوارئ',
      analyzedAt: '2026-02-19',
    },
  },
  {
    id: 'rh-prod-15',
    name: 'Boho Chic Macrame & Bamboo Event Lounge Set (4 Chairs + Table)',
    nameAr: 'طقم جلسة بوهو شيك للمناسبات وجلسات التصوير (4 كراسي خيزران + طاولة)',
    category: 'Furnishings',
    categoryAr: 'المفروشات والديكور',
    brand: 'Artisan Nile Crafts',
    model: 'Bohemian Sunset Event Lounge',
    purchaseYear: 2024,
    usageDuration: '4 events',
    usageDurationAr: '4 مناسبات فقط',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً ومعقم',
    originalPrice: 28000,
    dailyPrice: 350,
    weeklyPrice: 1800,
    securityDeposit: 1000,
    isAvailable: true,
    governorate: 'Alexandria',
    governorateAr: 'الإسكندرية',
    area: 'Kafr Abdo',
    areaAr: 'كفر عبده',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 4.9,
    reviewsCount: 15,
    isIdentityVerified: true,
    isProductReviewed: true,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-05',
    ownerName: 'Nouran Mostafa',
    ownerNameAr: 'نوران مصطفى',
    ownerRating: 5.0,
    ownerCompletedRentals: 21,
    specifications: {
      'Materials': 'Natural treated bamboo rattan & Egyptian organic macrame cotton',
      'Set Pieces': '4x Peacock armchairs + 1x Glass-top bamboo coffee table',
      'Cushions': 'High-density foam with water-repellent beige covers',
      'Use Cases': 'Weddings, baby showers, beach setups, rooftop parties',
    },
    specificationsAr: {
      'المواد': 'خيزران طبيعي معالج وخيوط مكرمية قطن مصري فاخر',
      'القطع': '4 كراسي طاووس ملكية + طاولة دائرية بسطح زجاجي معالج',
      'الشلت': 'إسفنج مضغوط عالي الكثافة مع أغطية بيج طاردة للماء',
      'الاستخدام': 'كتب كتاب، جلسات تصوير فوتوسيشن، حفلات خطوبة',
    },
    includedAccessories: [
      '4x decorative embroidered throw pillows',
      '1x woven jute floor rug (2x3 meters)',
      'Protective transport bubble-wrap covers',
    ],
    serialNumber: 'BOH-ST-44109-EG',
    approvalStatus: 'approved',
    aiInspection: {
      conditionScore: 96,
      visibleDamage: 'Zero cane fractures, spotless clean fabric cushions',
      visibleDamageAr: 'الخيزران خالي من أي تشققات، الشلت نظيفة وخالية من البقع',
      completeness: 'Complete 6-piece bundle including rug & cushions',
      completenessAr: 'مكتمل بجميع القطع والسجادة والوسائد الديكورية',
      imageQuality: 'Textile and structural inspection verified',
      imageQualityAr: 'تم توثيق المتانة ونظافة النسيج بنجاح',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Approved for premium photo sessions',
      recommendationAr: 'معتمد لجلسات التصوير والمناسبات الراقية',
      analyzedAt: '2026-02-05',
    },
  },
  {
    id: 'rh-prod-16',
    name: 'Pending Review: Breville Barista Touch Espresso Machine',
    nameAr: 'قيد المراجعة: ماكينة قهوة إسبريسو بريفيل باريستا تاتش بشاشة ذكية',
    category: 'Home Appliances',
    categoryAr: 'الأجهزة المنزلية',
    brand: 'Breville / Sage',
    model: 'Barista Touch BES880',
    purchaseYear: 2024,
    usageDuration: '2 months',
    usageDurationAr: 'شهران فقط',
    condition: 'Like New',
    conditionAr: 'كالجديد تماماً',
    originalPrice: 44000,
    dailyPrice: 220,
    weeklyPrice: 1150,
    securityDeposit: 1200,
    isAvailable: false,
    governorate: 'Ismailia',
    governorateAr: 'الإسماعيلية',
    area: 'Al Araysheya',
    areaAr: 'العرايشية',
    images: [
      'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
    ],
    rating: 0,
    reviewsCount: 0,
    isIdentityVerified: true,
    isProductReviewed: false,
    isDeliveryAvailable: true,
    isPaymentProtected: true,
    ownerId: 'user-own-01',
    ownerName: 'Tarek Mansour',
    ownerNameAr: 'طارق منصور',
    ownerRating: 4.95,
    ownerCompletedRentals: 47,
    specifications: {
      'Touchscreen': 'Automated swipe & select coffee menu',
      'Grinder': 'Integrated conical burr grinder with 30 grind settings',
      'Heating': 'ThermoJet system heating up in 3 seconds',
      'Milk': 'Auto steam wand with 8 micro-foam textures',
    },
    specificationsAr: {
      'الشاشة': 'شاشة لمس ذكية لاختيار وتخصيص مشروبات القهوة',
      'المطحنة': 'مطحنة حبوب مدمجة بتروس مخروطية مع 30 درجة طحن',
      'التسخين': 'نظام تسخين ThermoJet جاهز للتحضير في 3 ثوانٍ',
      'تبخير الحليب': 'عصا تبخير أوتوماتيكية بـ 8 مستويات لرغوة الميكروفوم',
    },
    includedAccessories: [
      '54mm stainless steel portafilter',
      'Stainless steel milk jug with temp sensor',
      'Cleaning kit & water filter',
    ],
    serialNumber: 'BRV-TOUCH-8812-EG',
    approvalStatus: 'pending_admin_review',
    aiInspection: {
      conditionScore: 86,
      visibleDamage: 'Minor superficial water mark on drip tray grill',
      visibleDamageAr: 'أثر مائي سطحي خفيف جداً على صينية تصريف المياه',
      completeness: 'Likely complete with portafilter and tamper',
      completenessAr: 'مكتملة على الأرجح مع البورتافلتر والتامبر الأصلي',
      imageQuality: 'Good multi-angle verification',
      imageQualityAr: 'صور جيدة من زوايا متعددة ومقبولة',
      riskLevel: 'Low',
      riskLevelAr: 'منخفض المخاطر',
      recommendation: 'Manual Review Recommended',
      recommendationAr: 'يوصى بالمراجعة الإدارية اليدوية للتأكد من الملحقات',
      analyzedAt: '2026-03-05',
    },
  },
];

export const INITIAL_BOOKINGS: RentalBooking[] = [
  {
    id: 'BK-2026-9041',
    productId: 'rh-prod-01',
    product: INITIAL_PRODUCTS[0],
    renterId: 'renter-cur-01',
    renterName: 'Karim Adel',
    renterNameAr: 'كريم عادل',
    startDate: '2026-03-10',
    endDate: '2026-03-13',
    daysCount: 3,
    dailyRate: 50,
    rentalCost: 150,
    deliveryFee: 50,
    securityDeposit: 500,
    platformFee: 20,
    totalAmount: 720,
    status: 'rental_active',
    createdAt: '2026-03-08T10:15:00Z',
    paymentMethod: 'credit_card',
    paymentStatus: 'secured',
    deliveryTrackingNumber: 'RB-EG-884102',
    courierName: 'RentBack Express / Bosta Logistics',
    deliveryEstimatedDate: '2026-03-10',
    pickupAddress: 'Al Sheikh Zayed, Ismailia, Villa 14',
    deliveryAddress: 'Al Montazah District, Ismailia, Building 22',
    beforeInspection: {
      inspectionDate: '2026-03-09',
      inspectorName: 'Hany Saber (RentBack Certified Inspector)',
      photos: [
        'https://images.unsplash.com/photo-1584269600464-37b1b58a9fe7?auto=format&fit=crop&w=600&q=80',
        'https://images.unsplash.com/photo-1585659722983-3a675dabf23d?auto=format&fit=crop&w=600&q=80',
      ],
      conditionNotes: 'Iron steam chambers checked. Zero scaling. Cord flexibility verified.',
      conditionNotesAr: 'تم فحص قنوات البخار للمكواة، خالية من التكلسات، السلك في حالة ممتازة.',
      defectsFound: ['Microscopic hairline rub mark on base rim'],
      defectsFoundAr: ['أثر احتكاك مجهري سطحي على الحافة السفلية'],
      accessoriesPresent: ['Original measuring cup', 'Heat storage bag'],
      accessoriesPresentAr: ['كوب الملء الأصلي', 'حقيبة الحفظ الحرارية'],
      functionalStatus: 'Flawless',
    },
  },
  {
    id: 'BK-2026-8910',
    productId: 'rh-prod-02',
    product: INITIAL_PRODUCTS[1],
    renterId: 'renter-cur-01',
    renterName: 'Karim Adel',
    renterNameAr: 'كريم عادل',
    startDate: '2026-03-15',
    endDate: '2026-03-17',
    daysCount: 2,
    dailyRate: 750,
    rentalCost: 1500,
    deliveryFee: 60,
    securityDeposit: 3000,
    platformFee: 60,
    totalAmount: 4620,
    status: 'owner_confirmed',
    createdAt: '2026-03-07T14:30:00Z',
    paymentMethod: 'mobile_wallet',
    paymentStatus: 'secured',
    deliveryTrackingNumber: 'RB-EG-773291',
    courierName: 'RentBack Express Pro Delivery',
    deliveryEstimatedDate: '2026-03-15',
    pickupAddress: 'Tagamoa 5, New Cairo',
    deliveryAddress: 'Dokki, Giza',
  },
  {
    id: 'BK-2026-7811',
    productId: 'rh-prod-04',
    product: INITIAL_PRODUCTS[3],
    renterId: 'renter-cur-01',
    renterName: 'Karim Adel',
    renterNameAr: 'كريم عادل',
    startDate: '2026-02-20',
    endDate: '2026-02-23',
    daysCount: 3,
    dailyRate: 120,
    rentalCost: 360,
    deliveryFee: 50,
    securityDeposit: 800,
    platformFee: 20,
    totalAmount: 1230,
    status: 'completed',
    createdAt: '2026-02-18T09:00:00Z',
    paymentMethod: 'credit_card',
    paymentStatus: 'released',
    deliveryTrackingNumber: 'RB-EG-551029',
    courierName: 'RentBack Express',
    deliveryEstimatedDate: '2026-02-20',
    pickupAddress: 'Smouha, Alexandria',
    deliveryAddress: 'Gleem, Alexandria',
    beforeInspection: {
      inspectionDate: '2026-02-19',
      inspectorName: 'RentBack QA Team',
      photos: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80'],
      conditionNotes: 'Batteries holding full charge. Drill chuck ratchets tightly.',
      conditionNotesAr: 'البطاريتان تشحنان بالكامل، ظرف الشنيور يعمل بقوة وسلاسة.',
      defectsFound: ['Normal outer bumper scuffs'],
      defectsFoundAr: ['آثار احتكاك عادية على الحواف المطاطية الخارجية'],
      accessoriesPresent: ['2 batteries', 'Charger', '30 drill bits', 'Bag'],
      accessoriesPresentAr: ['بطاريتان', 'شاحن سريع', '30 بنطة', 'حقيبة قماشية'],
      functionalStatus: 'Flawless',
    },
    afterInspection: {
      inspectionDate: '2026-02-23',
      inspectorName: 'RentBack Return QA Center',
      photos: ['https://images.unsplash.com/photo-1504148455328-c376907d081c?auto=format&fit=crop&w=600&q=80'],
      conditionNotes: 'Returned in identical operating condition. Cleaned and verified.',
      conditionNotesAr: 'تم استلام المعدة بنفس الحالة التشغيلية دون تلفيات. نظيفة وجاهزة.',
      defectsFound: [],
      defectsFoundAr: [],
      accessoriesPresent: ['2 batteries', 'Charger', '30 drill bits', 'Bag'],
      accessoriesPresentAr: ['جميع القطع الـ 30 والبطاريات والشاحن تم تسليمها كاملة'],
      functionalStatus: 'Flawless',
    },
  },
];

export const INITIAL_DISPUTES: DamageDispute[] = [
  {
    id: 'DSP-2026-001',
    bookingId: 'BK-2026-6701',
    productId: 'rh-prod-03',
    productName: 'Sony PlayStation 5 Console + 2 Controllers',
    productNameAr: 'بلايستيشن 5 مع ذراعين تحكم',
    renterName: 'Mahmoud Hassan',
    renterNameAr: 'محمود حسن',
    ownerName: 'Omar Farouk',
    ownerNameAr: 'عمر فاروق',
    status: 'Under Review',
    damagePhotos: [
      'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=600&q=80',
    ],
    damageDescription:
      'Controller #2 left analog stick was returned with physical drift and casing crack near R2 trigger.',
    damageDescriptionAr:
      'تم إرجاع ذراع التحكم الثاني وبه كسر واضح في الإطار بجوار زر R2 مع انحراف دائم في عصا التحكم التناظرية اليسرى.',
    estimatedRepairCost: 450,
    submittedAt: '2026-03-06T12:00:00Z',
  },
];

export const INITIAL_NOTIFICATIONS: AppNotification[] = [
  {
    id: 'notif-01',
    title: 'Identity Verified Successfully',
    titleAr: 'تم توثيق هويتك الوطنية بنجاح',
    message: 'Your National ID has been reviewed and verified by RentBack Trust & Safety.',
    messageAr: 'تم فحص بطاقة الرقم القومي والمطابقة الحيوية بنجاح. حسابك الآن موثق بالكامل ويمكنك التأجير بحرية.',
    timestamp: '10 mins ago',
    read: false,
    type: 'identity_verification',
  },
  {
    id: 'notif-02',
    title: 'Payment Secured for Booking #BK-9041',
    titleAr: 'تم حجز وتأمين الدفع للحجز #BK-9041',
    message: '720 EGP held securely in platform rental protection. Owner has confirmed pickup.',
    messageAr: 'مبلغ 720 ج.م محفوظ بأمان في نظام حماية التأجير للمنصة. أكد المالك موعد الاستلام.',
    timestamp: '1 hour ago',
    read: false,
    type: 'payment',
    bookingId: 'BK-2026-9041',
  },
  {
    id: 'notif-03',
    title: 'Courier Dispatched & En Route',
    titleAr: 'مندوب الشحن في الطريق للاستلام والتسليم',
    message: 'Courier Captain Mostafa is on the way with your Philips Azur Steam Iron.',
    messageAr: 'الكابتن مصطفى مندوب الشحن المعتمد في طريقه لتسليم مكواة فيليبس البخارية.',
    timestamp: '2 hours ago',
    read: false,
    type: 'delivery',
    bookingId: 'BK-2026-9041',
  },
  {
    id: 'notif-04',
    title: 'Product AI Inspection Completed',
    titleAr: 'اكتمل الفحص الذكي لمنتجك الجديد',
    message: 'Breville Barista Touch scored 86/100 and entered Pending Admin Review.',
    messageAr: 'ماكينة بريفيل حققت نتيجة فحص 86/100 ونُقلت لقسم المراجعة الإدارية للتدقيق النهائي.',
    timestamp: 'Yesterday',
    read: true,
    type: 'product_inspection',
  },
  {
    id: 'notif-05',
    title: 'Owner Payout Released: 360 EGP',
    titleAr: 'تم تحويل مستحقات المالك: 360 ج.م',
    message: 'Rental completed with zero damage. Payout transferred to your digital wallet.',
    messageAr: 'اكتمل التأجير بنجاح بدون تلفيات. تم تحويل 360 ج.م إلى محفظتك الإلكترونية بنجاح.',
    timestamp: '3 days ago',
    read: true,
    type: 'payout',
  },
];
